### ISSUE TITLE
Error 503 (again)

### ISSUE THREAD

**Issue by solsticedhiver** [coolbho3k/manuf#31]
Same as #29 but now it's the wka file, ie.:

Updating the manuf file with `manuf -u` gives an excpetion (see #29, it's the same)

Moved to https://gitlab.com/wireshark/wireshark/-/raw/master/wka or somewhere else. But the old url is gone

**Comment by joshschmelzle** [comment]
Even with the error, it appears the manuf file is updated (check the modification timestamp on the manuf file).  Because the update function first tries retrieving and writing updates from the `MANUF_URL`, and then second the `WFA_URL` which errors out.

https://github.com/coolbho3k/manuf/blob/94a2c518f873aa8d83e3b3f261210ab8f1e4f3d3/manuf/manuf.py#L64-L65

**Comment by solsticedhiver** [comment]
ok. my bad.
but all those error are dirty in my console ;-) sorry /o\

may be a try/catch block ?

**Comment by coolbho3k** [comment]
I'll take a look.

**Comment by coolbho3k** [comment]
Try 1.1.4?

**Comment by joshschmelzle** [comment]
Works for me. Thanks @coolbho3k!

**Comment by coolbho3k** [comment]
I just noticed tests have been broken, I'll fix haha 

Need to give this project some more attention

**Comment by coolbho3k** [comment]
Seems like this is fixed, please use 1.1.5

**Comment by joshschmelzle** [comment]
I might be able to spare an hour here or there for a PR if you want help on anything. Just let me know.

**Comment by coolbho3k** [comment]
> I might be able to spare an hour here or there for a PR if you want help on anything. Just let me know.

Any bug fixes if you notice any / feature enhancements are welcome!
